// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsuwilbmixocxxvnmosq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdXdpbGJtaXhvY3h4dm5tb3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTAwNjEsImV4cCI6MjA2ODQyNjA2MX0.WRHKfh7_ImZBMbdF3XHH2owLBl-yQ3AKqFHiKLRIRbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});